version : “3”
services:
  web:
    image: cat-picture
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_DATABASE=spring_db
      - MYSQL_ROOT_PASSWORD=ENC(lrXyd9hb+oOrddYr/76aJQ==)
    restart: always

