spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${MYSQL_DB_NAME}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

autocomplete:
  min: 0
  max: 6
  count: 30
  delimiter: ยง

the-cat-api:
  url: https://api.thecatapi.com/
  key: ${CAT_API_KEY}


